### ISSUE TITLE
Weak key exchange groups and server signature algorithms

### ISSUE THREAD

**Issue by rbsec** [actuated/xsltsslscan#1]
The full list of key exchange groups and server signature algorithms that are flagged by sslscan as weak can be found here:

https://github.com/rbsec/sslscan/blob/master/sslscan.c#L5592
https://github.com/rbsec/sslscan/blob/master/sslscan.c#L5291

Note that we test for servers saying they support any signature algorithm by sending a request with the id `0xfdff` (which isn't a valid algorithm). This ID will be included in the XML output with the name `ANY` since version 2.0.0-beta6 (it was missing before as you'd found).

```xml
  <connection-signature-algorithm sslversion="TLSv1.3" name="ANY" id="0xfdff" />
```

**Comment by actuated** [comment]
Thanks, updated the XSLT to make those checks based on ID, including the "any signature algorithm" result.
